server:
  port: 8080

spring:
  application:
    name: fitness-ai-backend

  profiles:
    include: secrets

  # Configuración de subida de archivos (10MB)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Configuración de Base de Datos MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_ai_app?useSSL=false&serverTimezone=UTC
    username: root
    password: ${spring.datasource.password} # Viene del application-secrets.yml
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuración de JPA (Hibernate)
  jpa:
    hibernate:
      # 'update' permite a Spring actualizar el esquema si añadimos campos (sólo para desarrollo)
      ddl-auto: update 
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false

# Configuración de Inteligencia Artificial
gemini:
  api:
    key: ${gemini.api.key} # Viene del application-secrets.yml

# Configuración de Cloudinary (Subida de Imágenes)
cloudinary:
  cloud-name: "qzfawgle"
  api-key: "614733196551375"
  api-secret: ${cloudinary.api-secret} # Viene del application-secrets.yml
